# 에러 핸들링...

아오 에러 핸들링 솔직히 잘 모르겠고 어떻게 하는게 좋은지 여전히 잘 모르겠다 ㅠㅠ

아 내 코드 마음에 안들어 안들어 뭐가 마음에 안드는지 모르겠는데 마음에 안들어 그냥...

더 가독성 좋게 쓸 수 없을까 더 직관적으로.... 적당히 신경쓰고 다음으로 넘어가야 하는데 이게 잘 안된다 진짜 답답해 미치겠다!!!!!

어렵다 어려워...

방법을 대충은 알겠는데 프로덕션 레벨에서 잘, 짜임새 있게 에러핸들링 코드 짜는게 아직 잘 안된다.

방법을 찾고자 자료나 다른 사람들의 코드를 참고하면서 공부해보고자 한다.

## [5 Async + Await Error Handling Strategies](https://www.youtube.com/watch?v=wsoQ-fgaoyQ)

하나의 함수만 놓고 보면 간단해보이지만, 여러 개의 호출 등을 같이 처리하다보면 이런 저런게 복잡해진다. 특히 `things get tricky with scope`라고 언급했는데, 내가 오늘 겪은 문제도 이런 느낌의 문제였다는 생각이 확 들었다.

그리고 주제를 명확하게 표현하는 워딩을 알게 되었음.

`Catching rejective promises`. 맞다. Reject될 가능성이 있는 프로미스가 reject되는 케이스에 대해서 확 잡아채서 프로그램의 흐름을 원하는대로 컨트롤 하는 것이 목적이다.

그리고 이 다섯 가지 방법들은 다 유효한 error handling strategy 들이다. 다만 특정 상황에서는 아쉬운 점들이 존재하는 것을 이해하면 되는 듯 하다.

참고로 이 동영상에서 집중하는 것은 Promise가 reject되는 경우에 대한 처리이고, throw 키워드를 통해 발생한 exception에 대해서는 다루지 않는다는 점. 그 부분은 또 따로 공부가 필요하겠다.

### 비동기 함수와 비동기 함수를 호출하는 handler

```javascript
async function getCheese(shouldError = false) {
  // after 1 second, return an array of cheese or Reject with an error
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (shouldError) {
        return reject("Cheese sucks");
      }
      resolve(["cheddar", "brie", "gouda"]);
    }, 1); // async 행동만 mock하고 빨리 실행되도록 1밀리초로 설정
  });
}

// 클라이언트 사이드에서 비동기 호출을 await 키워드로 기다려서 데이터를 받아서 처리하거나, 뭔가 잘못된 경우 그에 따라서 처리하는 케이스를 의미하는 함수
async function handler(request) {
  // get the async data
  const cheese = await getCheese();

  if ("error??") {
    return new Response(`Error from getCheese`, { status: 500 });
  }

  return new Response(data, { status: 200 });
}
```

### 1. .then().catch()

resolve된 값을 Promise객체의 `then()`메서드의 첫 번째 인자로 받아서 처리하거나, reject된 결과를 `catch()`메서드로 받아서 처리하는 형태.

```javascript
getCheese()
  .then((cheeses) => {
    console.log(cheeses);
  })
  .catch((err) => console.log(err));

// handler에서 이런 패턴을 활용하고자 하면 함수가 아래처럼 변경되어서 구현되어야 한다.
// 포인트는 성공/실패에 따라서 각 메서드 별로 값을 반환해야되고, chaining의 결과인 값을 다시 return 하는 처리가 필요하다는 점
async function handler(request) {
  return getCheese() //Promise가 처리된 결과값 자체가 return 되어야 함
    .then((cheeses) => {
      console.log(cheeses);
      return new Response(data, { status: 200 }); // 성공 케이스 값 처리(then메서드 밖에서 값을 받아서 처리할 수 있도록)
    })
    .catch((err) => {
      return new Response(`Error from Above Promise`, { status: 500 });
    });
}
```

이정도 형태에서는 막 그렇게 보기 나쁘지 않지만, 조금 더 기능을 고도화 하려는 순간 금방 보기 힘들어진다. 그리고 scoping 문제도 있다. `then()`메서드와 `catch()`메서드 간 공유해야 되는 값이 있다면 어떻게 해야될까...? 머리가 아파지는거다.

### 2. try/catch

```javascript
// then catch 를 사용하지 않고, 그냥 처리되기를 기다려서 그 결과를 변수에 할당해서 사용하는 방법

// some code here
// let outerCheese; 값을 외부에 선언해둔뒤에 try블록 안에서 cheese를 할당하는 등의 처리방식이 흔하게 사용된다.
try {
  const cheese = await getCheese();
  console.log(cheese);
} catch (err) {
  console.log(err);
}
// some code here
```

`then().catch()` 방법에서 고민했던 scoping 문제가 여기서도 똑같이 발생할 수 있다. try catch 외부의 scope(some code here 부분) cheese 라던지, err 값이 접근하려면 별도의 변수를 선언해서 값을 할당하거나, var로 각 값을 선언하거나? 하는 등의 처리가 필요하다..(var는 정말 정확하게 쓰면 편하겠지만, 요즘은 거의 사용되지 않는다 프로그램 안정성 이슈로)

즉 여전히 scoping 이슈가 있다는 점.

### 3. 섞어서 사용하는 방법.

이 사람이 많이 사용했던 방법이라고 한다.

```javascript
// If it works The value is assigned to my cheat and something goes wrong. The The catch phrase deals the error.
const myCheese = await getCheese().catch((err) => console.log(err));

// good, but the code after the above code still runs despite of catch method running
```

But this method has a problem and the problem is that, even though there is an error code, the code after that is going to run. However, you could deal with that using a If else statement or something But still, there is some problem to this.

### 4. bring it to a single level

비동기 실행 바로 다음에 (같은 레벨에) 처리된 데이터나 reject된 데이터를 같이 반환받는 것이 목적

```javascript
async function asyncWrap(promise) {
  try {
    const data = await promise;
    return [data, undefined];
  } catch (err) {
    return [undefined, err];
  }
}

// 데이터랑 에러를 같이 받아서 사용할 수 있다.
// 성공하는 경우와 reject되는 경우를 다 처리할 수 있는 방식이다.
// 배열로 반환되므로 변수명을 마음대로 받아서 사용할 수 있다는 것도 장점
// 튜플 형태의 데이터를 활용하는 것이다.
// 튜플이란??
const [cheeseData, cheeseError2] = await asyncWrap(getCheese());

// 에러가 발생하는 경우에 처리
if (cheeseError2) {
  console.log(cheeseError2);
  return new Response(`Error from getCheese`, { status: 500 });
}
```

### 4-1. non-async

```javascript
// allSettled를 활용하는 방법이다.
const results = await Promise.allSettled([getCheese(), getCheese(true)]);
// allSettled는 모든 프로미스가 성공하든 실패하든 상관없이 모든 프로미스가 처리될 때까지 기다린다.
// 그리고 각 프로미스에 대한 결과를 담은 객체를 반환한다.

// 이를 활용한 방법
// method4-1. non-async
// returns a value if resolved, or a reason if rejected
// value if good, reason if bad
function wrapIt(promise) {
  return Promise.allSettled([promise]).then(function ([{ value, reason }]) {
    return [value, reason];
  });
}

// actual usage
const [cheeseData2, cheeseError3] = await wrapIt(getCheese()); // [['cheddar', 'brie', 'gouda'], undefined]
const [cheeseData3, cheeseError4] = await wrapIt(getCheese(true)); // [undefined, 'Cheese sucks']
```

`allSettled`메서드를 활용해서 비슷한 형태로 더 간단하게 코드를 작성하는 것이 가능하다.

사실 이 부분은 완전히 이해된 상태가 아니다. 다시 보면서 코드를 많이 써보고 이해하는 과정이 필요함

다만, 이 형태의 코드는 짧고 간결해보이기는 하는데, 이해하기가 어려워보이는게 문제같다. 같이 쓰기에는 좋지 않을 듯.

```javascript
// some people prefer returning a "Result" type
function wrapItObject(promise) {
  return Promise.allSettled([promise]).then(function ([{ value, reason }]) {
    return { data: value, error: reason };
  });
}

/// then get a result object
const result = await wrapItObject(getCheese());
if (result.error) {
  console.log(result.error);
  return new Response(`Error from getCheese`, { status: 500 });
}
console.log(result.data);
```

### 동영상에서 제시하는 공부거리 추가로 공부하기

마지막에 추천해준 라이브러리들도 조금 보고(코드 공부하기 좋아보인다.)

그리고 TypeScript나 메커니즘도 이해하는 시간을 추가로 가져보자.

### 공부하면서 느낀 점 한 가지

그래도 이번 달에 Promise랑 async functions등에 대해서 공부했던 내용이 보다 동영상을 잘 이해하는데 도움이 되었다. 역시 아는만큼 보인다는 게 맞다. 공부하지 않고 동영상을 봐도 도움이 되었겠지만 공부한걸 토대로 더 많은 것을 이해할 수 있었다. 최대한 많이 공부하자. 넓고 깊게 보고 이해하는 개발자가 되어야 한다.
