# async에 대해 이해가 안되는 부분

회사에서 코드를 짜다가, async 함수를 await 하지 않아서 값이 unresolved 객체로 처리되어서 발생한 버그때문에 10분 정도를 낭비했다.

근래에 의문이 들긴했는데, 이 참에 공부를 하고 넘어가야겠다.

`async-await`함수가 포함된 중첩함수에서, 어디까지 `async-await`로 처리를 해줘야 하는 것일까?

## async await가 포함된 함수들을 실행해보기.

먼저 어떻게 동작하는지 보기 위해서 내가 이해하고 있는 내용을 기반으로 코드를 짜서 실행해보았다.

내가 확인하고 싶은 부분은, 내부적으로 `await`키워드로 Promise의 실행을 대기하는 로직이 존재하는 함수를 호출하는 함수를 `async-await`로 처리해야하는가 이다.

```javascript
// Promise
function resolveAfter2Seconds() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(20);
    }, 3000);
  });
}

// async-await키워드를 통해서 처리한 비동기 로직이 존재하는 함수
async function getPromiseResult() {
  const result = await resolveAfter2Seconds();
  console.log(result);
}

// 이 때, getPromiseResult() 함수를 다른 함수 안에서 호출하면, 해당 함수는 async-await키워드를 가지고 getPromiseResult()함수를 호출해야할까?
// 알아보자.

function outerFunctionCallingAsyncFunction() {
  getPromiseResult();
  console.log("after result");

  // console.log("result in outerfunction"/);
}

outerFunctionCallingAsyncFunction(); // 호출 결과는..?
```

**내가 예상한 결과**

만약에 사지선다를 주고, `outerFunctionCallingAsyncFunction`함수 호출 시 코드의 실행 순서를 고르라고 하면 나는

- `getPromiseResult()`함수 내의 console.log가 먼저 찍힌 후에,
- `outerFunctionCallingAsyncFunction`의 console.log가 찍힌다.

를 선택했을 것이다.

왜 이렇게 생각했을까?

`getPromiseResult`함수가 await 키워드로 result를 기다리기 때문에, result를 기다려서 console에 찍은 다음에 `getPromiseResult`함수를 호출하는 다음 라인의 코드가 실행된다고 생각함.

**하지만 나는 틀렸다.**

코드를 실행하면 `outerFunctionCallingAsyncFunction`의 console.log가 먼저찍힌 후에, 약 2초 뒤에 `getPromiseResult`의 console.log가 찍힌다.

으잉? 내가 뭘 모르고 있는걸까?

이 지점에 내가 async 키워드와 비동기 로직의 사용에 관련해서 헷갈렸던 것들에 대한 답이 있지 않을까 싶다. 찾아보자.

## async, await 그리고 Promise 및 비동기 처리에 대한 Fact 알아보기.

- the `await` operator(연산자구나!) is used to wait for a Promise and get its fulfillment value. It can be used inside an async function or at the top level of a module

  - `await` operator makes a promise-returning function behave as though they're synchronous by suspending execution until the returned promise is fulfilled or rejected.
  - the resolved value of the promise is treated as the return value of the await expression.
  - `await` pauses the execution of **its surrounding async function** until the promise is settled.

- each time an `async function` is called, it returns a new Promise which will be
  - resolved with the value returned by the async function
  - rejected with an exception uncaught in the async function

아하 await는 promise를 반환하는 함수가 반환한 promise가 resolve 되거나 reject될 때까지 execution을 미루는거구나.

`await for the resolving/rejecting of the return promise of the operand function`

문서를 좀 읽다보니까 내가 어떤 부분을 놓치고 있는지 감이 와서, 모르는게 정확히 뭔지 파악하고 공부를 이어서 해야겠다.

## 모르는게 뭔지 파악

**1. await 키워드가 가지는 정확한 의미**

- await 키워드는 연산자, 우측에 오는 피연산자에 대한 연산 결과를 반환
- await 연산자는 피연산자에 따라서 다른 값을 반환한다.
  - 피연산자가 `Promise`이거나, `thenable object`인 경우 -> fulfillment value
  - `thenable`하지않은 경우 -> 해당 표현식의 값 자체를 반환

```javascript
async function checkAwaitOperand() {
  const value = "value";
  // resolveAfter2Seconds함수가 반환하는 Promise에 대해서 await
  const awaitedPromiseResult = await resolveAfter2Seconds();

  // 원시값인 1에 대해서 await
  const awaitedPrimitiveResult = await 1;

  // 변수에 대해서 await
  const awaitedVariable = await value;

  console.log(awaitedPromiseResult, awaitedPrimitiveResult, awaitedVariable);
}

// Promise에 대해서는 fulfillment의 결과인 resolve된 값을 반환하고
// thenable이 아닌 1에 대해서는 해당 표현식을 평가한 값을 반환
checkAwaitOperand(); // 20, 1, value
```

- await 키워드는 surrounding async 함수의 실행을 중지하고, promise가 settle되는 것을 기다림
- await 피연산자 Promise가 reject되면, await 표현식이 포함된 함수가 Stack trace에 기록된다.
- await의 피연산자인 표현식은 Promise.resolve()와 같은 방식으로 resolve됨.

  - 그게 어떤 방식이냐? native한 Promise로 변환된 이후에 await된다.
  - expression의 종류에 따라서...
    - Native Promise -> 바로 사용되어서 native하게 await됨
    - Thenable 객체 -> 새로운 Promise를 구축해서 처리
    - non-thenable value -> 이미 fulfill 된 Promise가 구축되어서 사용됨.

- Promise가 바로 resolve되더라도, async 함수의 실행은 다음 `tick`까지 일시정지됨. -> 이 시간동안은 해당 async함수의 호출자가 execution을 이어나간다.(내가 이해가 안되는 부분에 대한 실마리가 여기 조금 있음.)

```javascript
// Error:
// at checkAwaitError 라고 함수명이 콘솔에 같이 찍힌다.
async function checkAwaitError() {
  try {
    await Promise.reject(new Error("error"));
  } catch (e) {
    console.log(e);
  }
}
```

**2. await 연산자가 존재하는 async function이 동작하는 flow**

코드 실행 중에 `await`키워드가 실행되면, await된 표현식이 실행되고 해당 expression의 값에 의존하는 모든 코드는 pause된 이후에 microtask queue에 push됨.

그리고 메인스레드는 다시 free되어서 event loop의 다음 작업을 이어서 실행한다.

await 키워드가 없는 경우, async키워드가 붙은 함수여도 사실상 동기적으로 실행된다.

하지만 await키워드가 하나라도 있다면, 첫 번째 await이전까지 코드들은 동기적으로 실행되지만 await이후의 코드는 다음 tick으로 이연된다.(이연?ㅋㅋㅋ)

여기서 한 가지.

await 연산자의 표현식은 바로 실행되지만, 그 이후의 코드가 await에 붙은 Promise가 resolve될 때까지 다음 코드의 실행은 일시정지 된다.
await 연산자 표현식은 바로 실행된다는 점이 흐름 이해의 포인트 한가지임. + await의 피연산자가 바로 resolve되는 표현식인 경우에도 실행 자체는 한 틱 뒤로 미뤄진다는 점.

다음 코드를 처음 봤을 때, 실행 흐름을 잘못 이해하고 있었음.

내 생각은 이랬다.

- First start - Second Start - First middle - First end - Second middle - Second end

왜냐하면, await 이후의 코드가 기다려진다고 생각했기 때문이다.

하지만 내가 잘못 이해한 부분은 `await 이후의 코드가 기다려진다`라는 부분이다. 역시 정확하게 알아야 하는구만.

await 표현식까지는 실행이 되고, 이 표현식이 어떤 코드인지에 따라서 실행이 달라지는 부분이 있다.

그 이후의 코드는 무조건 최소 한 틱 이후에 실행된다.

하지만 await의 피연산자는 실행 자체는 동기적으로 이뤄진다.(하지만 Promise라면, resolve되는 시점에 따라서 실행이 미뤄져서 늦게 실행되는 것처럼 착각이 될 수 있다. 나도 그랬고.) 그리고 실행되었을 때 console.log는 동기적으로 실행되는 로직이므로 바로 처리가 된다.

하지만 그 이후 코드는 한틱 무조건 지연되므로, await다음 부분이 실행되기 전에 foo(first)의 caller에게 execution이 넘어가서 foo(second)가 실행되어서 로직이 according하게 실행이 된다.

```javascript
async function foo(name) {
  console.log(name, "start");
  await console.log(name, "middle");
  console.log(name, "end");
}

foo("First");
foo("Second");

// First start
// First middle
// Second start
// Second middle
// First end
// Second end
```
